import { esc, initials, member } from './core.js';
import { icon } from './icons.js';

const SECTIONS=['main','extra','side'];
const LABELS={main:'Main Deck',extra:'Extra Deck',side:'Side Deck'};
const DRAFTS_KEY='fpt-cards-deck-drafts-v1';

export class DeckController {
  constructor({api,getState,searchCards,findCard,findCardById,tcgBanlistStatuses,isOnline,onRender,onToast,onLoansChanged}={}){
    Object.assign(this,{api,getState,searchCards,findCard,findCardById,tcgBanlistStatuses,isOnline,onRender,onToast,onLoansChanged});
    this.activeId='';this.targetSection='main';this.searchResults=[];this.searchTimer=0;this.importOpen=false;this.printingPicker=null;this.busy=false;this.error='';
  }
  get state(){return this.getState();}
  get decks(){return (this.state.decks||[]).filter(deck=>deck.game===this.state.game);}
  active(){return this.decks.find(deck=>deck.id===this.activeId)||this.decks[0]||null;}
  async load(){let remote=[],failure=null;try{remote=(await this.api.decks()||[]).map(mapDeck);}catch(error){failure=error;remote=this.state.decks||[];}const local=readDrafts().filter(deck=>deck.ownerSlug===this.state.currentUser),merged=new Map(remote.map(deck=>[deck.id,deck]));for(const draft of local)if(draft.dirty||!draft.persisted)merged.set(draft.id,draft);this.state.decks=[...merged.values()];await this.refreshTcgBanlist();if(!this.decks.some(deck=>deck.id===this.activeId))this.activeId=this.decks[0]?.id||'';if(failure)throw failure;return this.state.decks;}
  async refreshTcgBanlist(){if(!this.tcgBanlistStatuses||!(this.state.decks||[]).some(deck=>deck.game==='yugioh'))return;const statuses=await this.tcgBanlistStatuses();if(!statuses)return;for(const deck of this.state.decks||[]){if(deck.game!=='yugioh')continue;for(const card of deck.cards||[])card.banTcg=statuses[String(card.catalogCardId)]||'';}}
  view(){const deck=this.active();return `<section class="page-stack deck-page"><header class="deck-hero"><div><span class="eyebrow">Mazzi</span><h1>${deck?'Costruisci il tuo mazzo':'Crea il tuo mazzo'}</h1><p>Crea o importa una lista e verifica subito la disponibilità con il team.</p></div><div class="deck-hero-actions"><button class="btn" data-deck-new>${icon('plus')} Nuovo mazzo</button><button class="btn secondary" data-deck-import>${icon('logout')} Importa lista / YDK</button></div></header>${this.error?`<div class="connection-banner error">${esc(this.error)}</div>`:''}${deck?this.editor(deck):this.emptyView()}${this.importOpen?this.importView():''}${this.printingPicker?this.printingPickerView():''}</section>`;}
  emptyView(){return `<section class="surface deck-empty">${icon('deck')}<h2>Il tuo primo mazzo parte da qui</h2><p>Aggiungi le carte dal catalogo oppure importa un file .ydk o una lista testuale.</p><button class="btn" data-deck-new>${icon('plus')} Crea mazzo</button></section>`;}
  editor(deck){const report=deckAvailability(deck,this.state.collection,this.state.currentUser),total=deck.cards.reduce((sum,item)=>sum+item.quantity,0);return `<div class="deck-workspace"><div class="deck-main"><section class="surface deck-titlebar"><div>${deck.cover?`<img src="${esc(deck.cover)}" alt="">`:icon('deck')}<span><input data-deck-name value="${esc(deck.name)}" maxlength="80" aria-label="Nome mazzo"><small>Formato: ${esc(deck.format||'TCG Avanzato')}</small></span></div><div class="actions"><button class="btn secondary small" data-deck-save ${this.busy?'disabled':''}>${this.busy?'Salvataggio…':'Salva'}</button><button class="btn secondary small danger" data-deck-delete ${deck.persisted?'':'disabled'}>${icon('trash')} Elimina</button></div></section>
      <section class="surface deck-summary"><div><small>Totale carte</small><strong>${total}</strong></div>${SECTIONS.map(section=>`<div><small>${LABELS[section]}</small><strong>${sectionTotal(deck,section)}</strong></div>`).join('')}<div class="deck-ready"><small>Disponibilità personale</small><strong>${report.percent}%</strong><i style="--ready:${report.percent}"></i></div></section>
      <section class="deck-builder surface"><div class="deck-card-search"><label>${icon('search')}<input data-deck-search autocomplete="off" placeholder="Cerca una carta da aggiungere…"></label><select data-deck-target aria-label="Sezione di destinazione"><option value="main" ${this.targetSection==='main'?'selected':''}>Main (Extra automatico)</option><option value="side" ${this.targetSection==='side'?'selected':''}>Side Deck</option><option value="extra" ${this.targetSection==='extra'?'selected':''}>Extra Deck</option></select><div data-deck-search-results class="deck-search-results"></div></div><div class="deck-all-sections">${SECTIONS.map(section=>this.cardGrid(deck,section)).join('')}</div></section>
    </div><aside class="deck-availability"><section class="surface availability-head"><span>${icon('collection')}</span><div><small>Disponibilità team</small><strong>${report.percent}% pronto</strong></div><i style="--ready:${report.percent}"></i></section><section class="surface"><div class="section-heading"><div><h2>Carte mancanti o parziali</h2><p>Il proprietario proposto è quello con più copie disponibili.</p></div></div><div class="missing-card-list">${report.rows.length?report.rows.map(row=>missingRow(row,this.state.currentUser)).join(''):'<div class="deck-all-ready">✓ Tutte le carte sono disponibili nella tua raccolta.</div>'}</div>${report.requestable?`<button class="btn wide" data-deck-request-all ${this.busy||!this.isOnline()?'disabled':''}>${icon('swap')} Richiedi tutte le carte mancanti</button>`:''}</section></aside></div>
    ${this.decks.length>1?`<section class="surface recent-decks"><div class="section-heading"><div><h2>I tuoi mazzi</h2><p>Passa rapidamente a un’altra lista.</p></div></div><div>${this.decks.map(item=>`<button data-deck-open="${esc(item.id)}" class="${item.id===deck.id?'active':''}">${item.cover?`<img src="${esc(item.cover)}" alt="">`:icon('deck')}<span><strong>${esc(item.name)}</strong><small>${item.cards.reduce((sum,card)=>sum+card.quantity,0)} carte</small></span></button>`).join('')}</div></section>`:''}`;}
  cardGrid(deck,section){const cards=deck.cards.filter(item=>item.section===section);return `<section class="deck-zone ${section}"><header><strong>${LABELS[section]}</strong><span>${sectionTotal(deck,section)}</span></header>${cards.length?`<div class="deck-card-grid">${cards.map(item=>`<article><div class="deck-card-art">${item.imageUrl?`<img src="${esc(item.imageUrl)}" alt="${esc(item.cardName)}" loading="lazy">`:icon('card')}${restrictionBadge(item.banTcg)}<b>${item.quantity}</b></div><strong>${esc(item.cardName)}</strong><small>${esc(item.catalogCardId)}</small><button class="deck-printing-status ${item.printingId?'resolved':'unresolved'}" data-deck-printing="${esc(item.catalogCardId)}" data-deck-printing-section="${section}">${item.printingId?`${esc(item.printingSetCode||'Printing selezionata')}${item.printingRarity?` · ${esc(item.printingRarity)}`:''}`:'Printing da selezionare'}</button><div><button data-deck-qty="minus" data-deck-card="${esc(item.catalogCardId)}" data-deck-card-section="${section}" aria-label="Rimuovi una copia">−</button><span>${item.quantity}</span><button data-deck-qty="plus" data-deck-card="${esc(item.catalogCardId)}" data-deck-card-section="${section}" aria-label="Aggiungi una copia">+</button></div></article>`).join('')}</div>`:`<div class="deck-section-empty">${icon('card')}<span>Nessuna carta</span></div>`}</section>`;}
  importView(){return `<div class="detail-backdrop" data-deck-import-close><aside class="card-detail deck-import" role="dialog" aria-modal="true"><button class="detail-close" data-deck-import-close aria-label="Chiudi">×</button><span class="eyebrow">Importazione</span><h2>Carica un mazzo</h2><p>Supporta file .ydk, passcode Yu-Gi-Oh! e liste del tipo “3 Nome carta”.</p><label>File YDK o testo<input type="file" data-deck-file accept=".ydk,.txt,text/plain"></label><label>Oppure incolla la lista<textarea data-deck-import-text rows="12" placeholder="#main&#10;46986414&#10;46986414&#10;#extra&#10;..."></textarea></label><button class="btn wide" data-deck-import-run ${this.busy?'disabled':''}>${this.busy?'Importazione…':'Importa nel mazzo'}</button></aside></div>`;}
  printingPickerView(){const picker=this.printingPicker;return `<div class="detail-backdrop" data-deck-printing-close><aside class="card-detail deck-printing-picker" role="dialog" aria-modal="true"><button class="detail-close" data-deck-printing-close aria-label="Chiudi">×</button><span class="eyebrow">Market Watch</span><h2>Seleziona la printing</h2><p>${esc(picker.cardName)} · nessuna scelta viene effettuata automaticamente.</p>${picker.loading?'<div class="deck-printing-loading"><span class="loading-spinner"></span> Caricamento printing…</div>':picker.error?`<div class="connection-banner error">${esc(picker.error)}</div>`:picker.options.length?`<div class="deck-printing-options">${picker.options.map(option=>`<button data-deck-printing-option="${esc(option.printingId)}">${option.imageUrl?`<img src="${esc(option.imageUrl)}" alt="">`:icon('card')}<span><strong>${esc(option.setCode||'Set non indicato')}</strong><small>${esc(option.setName||'Espansione non indicata')} · ${esc(option.rarity||'Rarità non indicata')}</small></span>${icon('arrow')}</button>`).join('')}</div>`:'<div class="empty-state compact"><h3>Nessuna printing disponibile</h3><p>Aggiungi prima una copia precisa alla Raccolta.</p></div>'}</aside></div>`;}
  bind(root=document){
    root.querySelectorAll('[data-deck-new]').forEach(button=>button.addEventListener('click',()=>this.create()));
    root.querySelector('[data-deck-save]')?.addEventListener('click',()=>void this.save());root.querySelector('[data-deck-delete]')?.addEventListener('click',()=>void this.remove());
    root.querySelector('[data-deck-name]')?.addEventListener('input',event=>{const deck=this.active();if(deck){deck.name=event.target.value;this.markDirty(deck);}});
    root.querySelectorAll('[data-deck-open]').forEach(button=>button.addEventListener('click',()=>{this.activeId=button.dataset.deckOpen;this.onRender();}));
    root.querySelector('[data-deck-search]')?.addEventListener('input',event=>this.search(event.target.value));
    root.querySelector('[data-deck-target]')?.addEventListener('change',event=>{this.targetSection=event.target.value;});
    root.querySelectorAll('[data-deck-qty]').forEach(button=>button.addEventListener('click',()=>this.quantity(button.dataset.deckCard,button.dataset.deckCardSection,button.dataset.deckQty==='plus'?1:-1)));
    root.querySelectorAll('[data-deck-printing]').forEach(button=>button.addEventListener('click',()=>void this.openPrintingPicker(button.dataset.deckPrinting,button.dataset.deckPrintingSection)));
    root.querySelectorAll('[data-deck-printing-close]').forEach(node=>node.addEventListener('click',event=>{if(event.target!==node&&!event.target.closest('.detail-close'))return;this.printingPicker=null;this.onRender();}));
    root.querySelectorAll('[data-deck-printing-option]').forEach(button=>button.addEventListener('click',()=>void this.choosePrinting(button.dataset.deckPrintingOption)));
    root.querySelectorAll('[data-deck-request]').forEach(button=>button.addEventListener('click',()=>void this.request(button.dataset.deckRequest)));
    root.querySelector('[data-deck-request-all]')?.addEventListener('click',()=>void this.requestAll());
    root.querySelectorAll('[data-deck-import]').forEach(button=>button.addEventListener('click',()=>{if(!this.active())this.create(false);this.importOpen=true;this.onRender();}));
    root.querySelectorAll('[data-deck-import-close]').forEach(node=>node.addEventListener('click',event=>{if(event.target!==node&&!event.target.closest('.detail-close'))return;this.importOpen=false;this.onRender();}));
    root.querySelector('[data-deck-file]')?.addEventListener('change',async event=>{const text=await event.target.files?.[0]?.text();const field=root.querySelector('[data-deck-import-text]');if(field&&text!=null)field.value=text;});
    root.querySelector('[data-deck-import-run]')?.addEventListener('click',()=>void this.importText(root.querySelector('[data-deck-import-text]')?.value||''));
  }
  create(render=true){const deck={id:`draft-${Date.now()}`,persisted:false,dirty:true,ownerSlug:this.state.currentUser,name:'Nuovo mazzo',format:'TCG Avanzato',game:this.state.game,cards:[],cover:''};this.state.decks=[deck,...(this.state.decks||[])];this.activeId=deck.id;this.persistDrafts();if(render)this.onRender();}
  search(query){clearTimeout(this.searchTimer);const box=document.querySelector('[data-deck-search-results]');if(!box)return;if(query.trim().length<3){box.innerHTML='';return;}box.innerHTML='<span>Ricerca…</span>';this.searchTimer=setTimeout(async()=>{const results=await this.searchCards(query,this.state.game);this.searchResults=results;const current=document.querySelector('[data-deck-search-results]');if(!current)return;current.innerHTML=results.map((card,index)=>`<button data-deck-result="${index}">${card.image?`<img src="${esc(card.image)}" alt="">`:''}<span><strong>${esc(card.name)}</strong><small>${esc(card.type||'Carta')}</small></span>${icon('plus')}</button>`).join('')||'<span>Nessuna carta trovata</span>';current.querySelectorAll('[data-deck-result]').forEach(button=>button.addEventListener('click',()=>this.add(this.searchResults[Number(button.dataset.deckResult)])));},260);}
  add(card,section=this.targetSection,quantity=1){const deck=this.active();if(!deck||!card)return;const destination=section==='main'&&isExtraDeckCard(card)?'extra':section,id=String(card.id),existing=deck.cards.find(item=>item.catalogCardId===id&&item.section===destination);if(existing){existing.quantity=Math.min(99,existing.quantity+quantity);existing.banTcg=card.banTcg||existing.banTcg||'';}else deck.cards.push({catalogCardId:id,cardName:card.name,imageUrl:card.fullImage||card.image||'',banTcg:card.banTcg||'',section:destination,quantity});deck.cover=deck.cover||card.fullImage||card.image||'';this.searchResults=[];this.markDirty(deck);this.onRender();}
  quantity(id,section,delta){const deck=this.active(),item=deck?.cards.find(card=>card.catalogCardId===id&&card.section===section);if(!item)return;item.quantity+=delta;if(item.quantity<=0)deck.cards=deck.cards.filter(card=>card!==item);this.markDirty(deck);this.onRender();}
  async openPrintingPicker(catalogCardId,section){const deck=this.active(),card=deck?.cards.find(item=>item.catalogCardId===catalogCardId&&item.section===section);if(!deck?.persisted)return this.onToast('Salva il mazzo prima di selezionare la printing');this.printingPicker={catalogCardId,section,cardName:card?.cardName||'Carta',loading:true,error:'',options:[]};this.onRender();try{const rows=await this.api.deckPrintingOptions(deck.id,catalogCardId);if(!this.printingPicker)return;this.printingPicker.options=(rows||[]).map(row=>({printingId:row.printing_id||row.printingId,setCode:row.set_code||row.setCode||'',setName:row.set_name||row.setName||'',rarity:row.rarity||'',imageUrl:row.image_url||row.imageUrl||''}));}catch(error){if(this.printingPicker)this.printingPicker.error=error.message||'Printing non disponibili';}finally{if(this.printingPicker)this.printingPicker.loading=false;this.onRender();}}
  async choosePrinting(printingId){const picker=this.printingPicker,deck=this.active();if(!picker||!deck)return;const option=picker.options.find(item=>item.printingId===printingId);this.busy=true;try{await this.api.setDeckCardPrinting(deck.id,picker.catalogCardId,picker.section,printingId);const card=deck.cards.find(item=>item.catalogCardId===picker.catalogCardId&&item.section===picker.section);if(card){card.printingId=printingId;card.printingSetCode=option?.setCode||'';card.printingRarity=option?.rarity||'';}this.printingPicker=null;this.onToast('Printing collegata al mazzo');}catch(error){this.onToast(error.message||'Selezione non riuscita');}finally{this.busy=false;this.onRender();}}
  async save(){const deck=this.active();if(!deck||!deck.name.trim()||!this.isOnline())return this.onToast('Nome del mazzo o connessione non disponibili');const oldId=deck.id;this.busy=true;this.onRender();try{const id=String(await this.api.saveDeck(deck)||oldId);this.clearDraft(oldId);await this.load();this.activeId=id;this.onToast('Mazzo salvato');}catch(error){this.error=error.message||'Salvataggio non riuscito';}finally{this.busy=false;this.onRender();}}
  async remove(){const deck=this.active();if(!deck?.persisted||!confirm(`Eliminare “${deck.name}”?`))return;this.busy=true;try{await this.api.deleteDeck(deck.id);this.clearDraft(deck.id);await this.load();this.activeId=this.decks[0]?.id||'';this.onToast('Mazzo eliminato');}catch(error){this.onToast(error.message||'Eliminazione non riuscita');}finally{this.busy=false;this.onRender();}}
  async importText(text){if(!text.trim())return this.onToast('Incolla una lista o seleziona un file');this.busy=true;this.onRender();try{const parsed=parseDeckList(text),resolved=new Map();for(const item of parsed){const key=item.id?`id:${item.id}`:`name:${item.name.toLowerCase()}`;if(resolved.has(key))continue;const card=item.id?await this.findCardById(item.id,'',this.state.game):await this.findCard(item.name,this.state.game);if(card)resolved.set(key,card);}for(const item of parsed){const card=resolved.get(item.id?`id:${item.id}`:`name:${item.name.toLowerCase()}`);if(card)this.addSilent(card,item.section,item.quantity);}if(!resolved.size)throw new Error('Nessuna carta valida trovata nella lista');this.importOpen=false;this.onToast(`${resolved.size} carte importate`);}catch(error){this.onToast(error.message||'Importazione non riuscita');}finally{this.busy=false;this.onRender();}}
  addSilent(card,section,quantity){const deck=this.active(),id=String(card.id),existing=deck.cards.find(item=>item.catalogCardId===id&&item.section===section);if(existing){existing.quantity+=quantity;existing.banTcg=card.banTcg||existing.banTcg||'';}else deck.cards.push({catalogCardId:id,cardName:card.name,imageUrl:card.fullImage||card.image||'',banTcg:card.banTcg||'',section,quantity});deck.cover=deck.cover||card.fullImage||card.image||'';this.markDirty(deck);}
  markDirty(deck){deck.dirty=true;deck.ownerSlug=this.state.currentUser;this.persistDrafts();}
  persistDrafts(){const current=readDrafts().filter(deck=>deck.ownerSlug!==this.state.currentUser),dirty=(this.state.decks||[]).filter(deck=>deck.ownerSlug===this.state.currentUser&&(deck.dirty||!deck.persisted));localStorage.setItem(DRAFTS_KEY,JSON.stringify([...current,...dirty]));}
  clearDraft(id){const next=readDrafts().filter(deck=>!(deck.ownerSlug===this.state.currentUser&&deck.id===id));localStorage.setItem(DRAFTS_KEY,JSON.stringify(next));}
  async request(cardId){const row=deckAvailability(this.active(),this.state.collection,this.state.currentUser).rows.find(item=>item.catalogCardId===cardId);if(!row?.best)return;this.busy=true;this.onRender();try{let remaining=row.missing;for(const item of row.best.items){const quantity=Math.min(remaining,item.quantityAvailable);if(quantity>0)await this.api.requestCollectionLoan(item.id,quantity,`Richiesta automatica dal mazzo ${this.active().name}`);remaining-=quantity;if(!remaining)break;}await this.onLoansChanged?.();this.onToast(`Richiesta inviata a ${row.best.ownerName}`);}catch(error){this.onToast(error.message||'Richiesta non riuscita');}finally{this.busy=false;this.onRender();}}
  async requestAll(){const rows=deckAvailability(this.active(),this.state.collection,this.state.currentUser).rows.filter(row=>row.best);for(const row of rows)await this.request(row.catalogCardId);}
}

export function deckAvailability(deck,collection,currentUser){const cards=deck?.cards||[],mine=new Map(),teamByCard=new Map();for(const item of collection?.mine||[])mine.set(String(item.catalogCardId),(mine.get(String(item.catalogCardId))||0)+Number(item.quantityAvailable||0));for(const item of collection?.team||[]){if(item.ownerSlug===currentUser||Number(item.quantityAvailable||0)<=0)continue;const id=String(item.catalogCardId);if(!teamByCard.has(id))teamByCard.set(id,new Map());const owners=teamByCard.get(id),entry=owners.get(item.ownerSlug)||{ownerSlug:item.ownerSlug,ownerName:item.ownerName,quantity:0,items:[]};entry.quantity+=Number(item.quantityAvailable||0);entry.items.push(item);owners.set(item.ownerSlug,entry);}const required=new Map();for(const card of cards){const id=String(card.catalogCardId),entry=required.get(id)||{...card,quantity:0};entry.quantity+=card.quantity;required.set(id,entry);}let total=0,covered=0,requestable=0;const rows=[];for(const card of required.values()){const owned=mine.get(String(card.catalogCardId))||0,missing=Math.max(0,card.quantity-owned),best=[...(teamByCard.get(String(card.catalogCardId))?.values()||[])].sort((a,b)=>b.quantity-a.quantity)[0]||null;total+=card.quantity;covered+=Math.min(card.quantity,owned);if(missing){if(best)requestable+=1;rows.push({...card,owned,missing,best});}}return {total,covered,percent:total?Math.round(covered/total*100):0,rows,requestable};}
export function parseDeckList(text){let section='main';const merged=new Map();for(const raw of String(text).split(/\r?\n/)){const line=raw.trim();if(!line)continue;const marker=line.toLowerCase();if(marker==='#main'||marker==='main deck'||marker==='main:'){section='main';continue;}if(marker==='#extra'||marker==='extra deck'||marker==='extra:'){section='extra';continue;}if(marker==='!side'||marker==='#side'||marker==='side deck'||marker==='side:'){section='side';continue;}if(line.startsWith('#')||line.startsWith('!'))continue;const match=line.match(/^(?:(\d{1,2})\s*[x×]?\s+)?(.+)$/),quantity=Math.max(1,Number(match?.[1]||1)),value=(match?.[2]||line).trim(),id=/^\d{5,10}$/.test(value)?value:'';const key=`${section}:${id||value.toLowerCase()}`,existing=merged.get(key);if(existing)existing.quantity+=quantity;else merged.set(key,{section,quantity,id,name:id?'':value});}return [...merged.values()];}
function mapDeck(row){return {id:String(row.id),persisted:true,dirty:false,ownerSlug:row.owner_slug||row.ownerSlug||'',name:row.name,format:row.format||'TCG Avanzato',game:row.game,cards:(row.cards||[]).map(card=>({catalogCardId:String(card.catalog_card_id||card.catalogCardId),cardName:card.card_name||card.cardName,imageUrl:card.image_url||card.imageUrl||'',banTcg:card.ban_tcg||card.banTcg||'',section:card.section||'main',quantity:Number(card.quantity||1),printingId:card.printing_id||card.printingId||null,printingSetCode:card.printing_set_code||card.printingSetCode||'',printingRarity:card.printing_rarity||card.printingRarity||''})),cover:row.cover_image_url||row.coverImageUrl||''};}
function readDrafts(){try{const value=JSON.parse(localStorage.getItem(DRAFTS_KEY)||'[]');return Array.isArray(value)?value:[];}catch{return[];}}
export function isExtraDeckCard(card){return /fusion|synchro|xyz|link/i.test(String(card?.type||''));}
function sectionTotal(deck,section){return deck.cards.filter(card=>card.section===section).reduce((sum,card)=>sum+card.quantity,0);}
function restrictionBadge(status){const badges={limited:['1','Limitata a 1 copia'],'semi-limited':['2','Semi-limitata a 2 copie'],forbidden:['⊘','Proibita']},badge=badges[status];return badge?`<i class="deck-ban-badge ${status}" title="${badge[1]} nel formato TCG Advanced" aria-label="${badge[1]} nel formato TCG Advanced">${badge[0]}</i>`:'';}
function missingRow(row,currentUser){const owner=row.best,profile=owner?member(owner.ownerSlug):null;return `<article class="missing-card"><div>${row.imageUrl?`<img src="${esc(row.imageUrl)}" alt="">`:icon('card')}<span><strong>${esc(row.cardName)}</strong><small>Possiedi ${row.owned} di ${row.quantity} · mancano ${row.missing}</small>${owner?`<em><i class="mini-avatar member-${esc(owner.ownerSlug)}">${initials(profile?.name||owner.ownerName||'?')}</i>${esc(owner.ownerName)} ne ha ${owner.quantity}</em>`:'<em>Nessuna copia disponibile nel team</em>'}</span></div>${owner?`<button class="btn secondary small" data-deck-request="${esc(row.catalogCardId)}" ${owner.ownerSlug===currentUser?'disabled':''}>Richiedi</button>`:''}</article>`;}
