import {esc} from './core.js';
import {icon} from './icons.js';
import {renderDeckBoxCard,renderDeckBoxVisual} from './deck-box.js';

const TABS=['owned','deck','manual'];
const LABELS={owned:'Owned',deck:'Deck',manual:'Watchlist'};
const FRESH_MS=48*60*60*1000;

export class MarketWatchController {
  constructor({api,getGame,getDecks,onRender,onToast,onNavigate}={}){Object.assign(this,{api,getGame,getDecks,onRender,onToast,onNavigate});this.data={items:[],deckUnresolved:[],lastSync:null};this.tab='owned';this.sort='value';this.loading=false;this.error='';this.selected='';this.selectedDeck='';this.history=new Map();this.featuredHistory=new Map();this.featuredLoading=new Set();this.featuredSync='';this.historyLoading=false;}
  async load(){this.loading=true;try{const game=this.getGame(),moversRequest=this.api.marketDashboardMovers?this.api.marketDashboardMovers(game).catch(()=>[]):Promise.resolve([]),[payload,movers]=await Promise.all([this.api.marketWatch(game),moversRequest]),next=mapPayload(payload);next.featuredMovers=mapDashboardMovers(movers);if(next.lastSync&&next.lastSync!==this.featuredSync){this.featuredHistory.clear();this.featuredSync=next.lastSync;}this.data=next;this.error='';void this.loadFeaturedHistories();}catch(error){this.error=/list_market_watch/i.test(error.message||'')?'Applica la migration Market Watch per attivare i dati.':(error.message||'Market Watch non disponibile');}finally{this.loading=false;}return this.data;}
  dashboardState(){return {...this.data,error:this.error,featuredHistory:this.featuredHistory};}
  async loadFeaturedHistories(){if(this.data.featuredMovers?.length)return;const missing=positiveMovers(this.data.items,3).filter(item=>!this.featuredHistory.has(item.printingId)&&!this.featuredLoading.has(item.printingId));if(!missing.length)return;missing.forEach(item=>this.featuredLoading.add(item.printingId));await Promise.all(missing.map(async item=>{try{const rows=await this.api.marketPriceHistory(item.printingId,30),history=(rows||[]).map(row=>({provider:row.provider,type:row.price_type||row.priceType,price:Number(row.price),capturedAt:row.captured_at||row.capturedAt})).filter(row=>row.provider==='cardmarket'&&row.type==='trend'&&Number.isFinite(row.price));this.featuredHistory.set(item.printingId,history);this.history.set(item.printingId,history);}catch{this.featuredHistory.set(item.printingId,[]);}finally{this.featuredLoading.delete(item.printingId);}}));this.onRender?.();}
  view(){const summary=portfolioSummary(this.data.items),items=sortItems(this.data.items.filter(item=>item.sources.includes(this.tab)),this.sort),unresolved=this.tab==='deck'?this.data.deckUnresolved:[],marketDecks=this.marketDecks(),hasSnapshots=this.data.items.some(item=>item.referencePrice!=null);
    return `<section class="page-stack market-page"><header class="market-hero"><div><span class="eyebrow">Valore e andamento</span><h1>Market Watch</h1><p>Segui le printing esatte della raccolta, dei mazzi e della watchlist.</p></div><div class="market-sync-state"><i class="${this.error?'error':this.data.lastSync?'ok':'waiting'}"></i><span><small>Ultimo aggiornamento</small><strong>${this.data.lastSync?formatTimestamp(this.data.lastSync):'In attesa del primo sync'}</strong></span></div></header>
      ${this.error?`<div class="connection-banner error">${esc(this.error)}</div>`:''}
      <section class="market-kpis">
        ${kpi('Valore raccolta',summary.complete?money(summary.current):'Dati parziali',summary.complete?`${summary.coveredUnits}/${summary.totalUnits} copie valorizzate`:`Dati parziali · ${summary.coveredPrintings}/${summary.totalPrintings} printing valorizzate`,'value')}
        ${kpi('Variazione 24h',summary.delta24Complete?changeMoney(summary.delta24):'Dati parziali',summary.delta24Complete?changePercent(summary.delta24Percent):'Snapshot non sufficiente',tone(summary.delta24))}
        ${kpi('Variazione 7d',summary.delta7Complete?changeMoney(summary.delta7):'Dati parziali',summary.delta7Complete?changePercent(summary.delta7Percent):'Snapshot non sufficiente',tone(summary.delta7))}
        ${kpi('Printing monitorate',String(this.data.items.length),`${summary.freshPrintings} aggiornate entro 48h`,'count')}
      </section>
      <section class="surface market-board"><div class="market-board-tools"><nav class="market-tabs" aria-label="Filtri Market Watch">${TABS.map(tab=>`<button data-market-tab="${tab}" class="${this.tab===tab?'active':''}">${LABELS[tab]} <span>${countFor(this.data,tab,marketDecks.length)}</span></button>`).join('')}</nav><label>Ordina<select data-market-sort><option value="value" ${this.sort==='value'?'selected':''}>Valore posseduto</option><option value="price" ${this.sort==='price'?'selected':''}>Prezzo più alto</option><option value="change" ${this.sort==='change'?'selected':''}>Variazione 24h</option><option value="name" ${this.sort==='name'?'selected':''}>Nome</option></select></label></div>
        ${this.tab==='deck'?this.deckRows(marketDecks):!this.data.items.length?emptyNoCards():!hasSnapshots?`${emptyPreparing()}${this.rows(items,[])}`:this.rows(items,[])}
      </section>${this.selected?this.detailView():''}${this.selectedDeck?this.deckDetailView(marketDecks):''}</section>`;}
  rows(items,unresolved){return `<div class="market-list">${unresolved.map(unresolvedDeckRow).join('')}${items.map(marketRow).join('')}${!items.length&&!unresolved.length?'<div class="market-tab-empty">Nessuna printing in questa sezione.</div>':''}</div>`;}
  marketDecks(){return buildMarketDecks(this.getDecks?.()||this.data.decks||[],this.data.items,this.data.deckUnresolved);}
  deckRows(decks){return decks.length?`<div class="market-deck-grid">${decks.map(deck=>renderDeckBoxCard(deck,{mode:'market',marketValue:deck.marketValue,delta24:deck.delta24,delta7:deck.delta7,topMover:deck.topMover})).join('')}</div>`:'<div class="market-tab-empty">Nessun mazzo disponibile nel Market Watch.</div>';}
  deckDetailView(decks){const deck=decks.find(row=>String(row.id)===String(this.selectedDeck));if(!deck)return'';return `<div class="detail-backdrop" data-market-deck-close><aside class="card-detail market-deck-detail" role="dialog" aria-modal="true"><button class="detail-close" data-market-deck-close aria-label="Chiudi">×</button><span class="eyebrow">Valore mazzo</span><div class="market-deck-detail-head">${renderDeckBoxVisual(deck)}<div><h2>${esc(deck.name)}</h2><p>${deck.marketValue==null?'Valore non disponibile':money(deck.marketValue)}</p><small>${deck.valuedCopies}/${deck.totalCopies} copie valorizzate${deck.unresolvedCount?` · ${deck.unresolvedCount} printing da definire`:''}</small></div></div><div class="market-deck-kpis"><span><small>24 ore</small><strong class="${tone(deck.delta24)}">${changePercent(deck.delta24)}</strong></span><span><small>7 giorni</small><strong class="${tone(deck.delta7)}">${changePercent(deck.delta7)}</strong></span><span><small>Top mover</small><strong>${deck.topMover?`${esc(deck.topMover.cardName)} ${changePercent(deck.topMover.percent)}`:'Non disponibile'}</strong></span></div><p class="data-note">Il valore deriva dalle printing collegate al mazzo. Le fonti restano visibili nei dettagli delle singole printing.</p></aside></div>`;}
  detailView(){const item=this.data.items.find(row=>row.printingId===this.selected);if(!item)return'';const providers=Object.entries(item.providers||{}),warning=providerWarning(item.providers),history=this.history.get(item.printingId)||[];
    return `<div class="detail-backdrop" data-market-detail-close><aside class="card-detail market-detail" role="dialog" aria-modal="true"><button class="detail-close" data-market-detail-close aria-label="Chiudi">×</button><div class="market-detail-head">${item.imageUrl?`<img src="${esc(item.imageUrl)}" alt="">`:icon('card')}<div><span class="eyebrow">Dettaglio printing</span><h2>${esc(item.cardName)}</h2><p>${esc(item.setCode||'Set non indicato')} · ${esc(item.rarity||'Rarità non indicata')}</p></div></div><section class="market-chart"><h3>Andamento 30 giorni</h3>${this.historyLoading?'<div class="loading-spinner"></div>':priceChart(history)}</section><h3>Valori provider</h3>${providers.length?`<div class="provider-price-list">${providers.map(([name,value])=>`<article><span><strong>${providerName(name)}</strong><small>${esc(value.type||'prezzo')} · ${formatTimestamp(value.capturedAt)}</small></span><b>${money(value.price)}</b><em>${esc(value.conditionReference||'Riferimento provider')}</em></article>`).join('')}</div>`:'<div class="market-detail-empty">Nessuno snapshot disponibile.</div>'}${warning?`<p class="provider-warning">${icon('info')} Prezzi discordanti tra marketplace (${warning}% di differenza).</p>`:''}<div class="market-detail-actions">${item.cardmarketUrl?`<a class="btn wide" href="${esc(item.cardmarketUrl)}" target="_blank" rel="noopener noreferrer">Apri su Cardmarket</a>`:`<p class="mapping-state">Mapping Cardmarket: ${esc(item.mappingStatus||'unresolved')}</p>`}${item.sources.includes('manual')?`<button class="btn secondary danger wide" data-market-unwatch="${esc(item.printingId)}">Rimuovi dalla Watchlist</button>`:''}</div></aside></div>`;}
  bind(root=document){root.querySelectorAll('[data-market-tab]').forEach(button=>button.addEventListener('click',()=>{this.tab=button.dataset.marketTab;this.selected='';this.selectedDeck='';this.onRender();}));root.querySelector('[data-market-sort]')?.addEventListener('change',event=>{this.sort=event.target.value;this.onRender();});root.querySelectorAll('[data-market-card]').forEach(button=>button.addEventListener('click',()=>void this.openDetail(button.dataset.marketCard)));root.querySelectorAll('[data-market-deck]').forEach(button=>button.addEventListener('click',()=>{this.selectedDeck=button.dataset.marketDeck;this.onRender();}));root.querySelectorAll('[data-market-deck-close]').forEach(node=>node.addEventListener('click',event=>{if(event.target!==node&&!event.target.closest('.detail-close'))return;this.selectedDeck='';this.onRender();}));root.querySelectorAll('[data-market-detail-close]').forEach(node=>node.addEventListener('click',event=>{if(event.target!==node&&!event.target.closest('.detail-close'))return;this.selected='';this.onRender();}));root.querySelectorAll('[data-market-unwatch]').forEach(button=>button.addEventListener('click',()=>void this.unwatch(button.dataset.marketUnwatch)));root.querySelectorAll('[data-market-resolve-deck]').forEach(button=>button.addEventListener('click',()=>this.onNavigate('decks')));}
  async openDetail(printingId){this.selected=printingId;this.onRender();if(this.history.has(printingId))return;this.historyLoading=true;this.onRender();try{const rows=await this.api.marketPriceHistory(printingId,30);this.history.set(printingId,(rows||[]).map(row=>({provider:row.provider,type:row.price_type||row.priceType,price:Number(row.price),capturedAt:row.captured_at||row.capturedAt})));}catch{this.history.set(printingId,[]);}finally{this.historyLoading=false;this.onRender();}}
  async unwatch(printingId){try{await this.api.setMarketWatchItem(printingId,false);await this.load();this.selected='';this.onToast('Printing rimossa dalla Watchlist');}catch(error){this.onToast(error.message||'Operazione non riuscita');}this.onRender();}
}

export function mapPayload(payload={}){return {items:(payload.items||[]).map(row=>({printingId:row.printing_id||row.printingId,catalogCardId:String(row.catalog_card_id||row.catalogCardId||''),cardName:row.card_name||row.cardName||'',setCode:row.set_code||row.setCode||'',setName:row.set_name||row.setName||'',rarity:row.rarity||'',imageUrl:row.image_url||row.imageUrl||'',sources:Array.isArray(row.sources)?row.sources:[],ownedQuantity:Number(row.owned_quantity??row.ownedQuantity??0),providers:normalizeProviders(row.providers),referencePrice:nullableNumber(row.reference_price??row.referencePrice),price24h:nullableNumber(row.price_24h??row.price24h),price7d:nullableNumber(row.price_7d??row.price7d),price30d:nullableNumber(row.price_30d??row.price30d),latestAt:row.latest_at||row.latestAt||null,mappingStatus:row.mapping_status||row.mappingStatus||'unresolved',cardmarketProductId:String(row.cardmarket_product_id||row.cardmarketProductId||''),cardmarketUrl:row.cardmarket_url||row.cardmarketUrl||''})),deckUnresolved:(payload.deckUnresolved||payload.deck_unresolved||[]).map(row=>({deckId:row.deckId||row.deck_id,deckName:row.deckName||row.deck_name,cardName:row.cardName||row.card_name,catalogCardId:String(row.catalogCardId||row.catalog_card_id||''),section:row.section,quantity:Number(row.quantity||0)})),lastSync:payload.lastSync||payload.last_sync||null};}
export function buildMarketDecks(decks=[],items=[],unresolved=[]){
  const prices=new Map((items||[]).map(item=>[String(item.printingId),item])),unresolvedByDeck=new Map();
  for(const row of unresolved||[])unresolvedByDeck.set(String(row.deckId),(unresolvedByDeck.get(String(row.deckId))||0)+Number(row.quantity||0));
  const available=(decks||[]).map(deck=>{
    let totalCopies=0,valuedCopies=0,current=0,current24=0,baseline24=0,current7=0,baseline7=0,has24=false,has7=false,topMover=null;
    for(const card of deck.cards||[]){const quantity=Number(card.quantity||0);totalCopies+=quantity;const item=card.printingId?prices.get(String(card.printingId)):null;if(!item||item.referencePrice==null)continue;valuedCopies+=quantity;current+=item.referencePrice*quantity;
      if(item.price24h!=null&&item.price24h>0){has24=true;current24+=item.referencePrice*quantity;baseline24+=item.price24h*quantity;const percent=(item.referencePrice-item.price24h)/item.price24h*100;if(!topMover||percent>topMover.percent)topMover={cardName:card.cardName,percent};}
      if(item.price7d!=null&&item.price7d>0){has7=true;current7+=item.referencePrice*quantity;baseline7+=item.price7d*quantity;}
    }
    return {...deck,marketValue:valuedCopies?current:null,delta24:has24&&baseline24?((current24-baseline24)/baseline24)*100:null,delta7:has7&&baseline7?((current7-baseline7)/baseline7)*100:null,topMover:topMover?.percent>0?topMover:null,totalCopies,valuedCopies,unresolvedCount:unresolvedByDeck.get(String(deck.id))||0};
  });
  if(available.length)return available;
  const grouped=new Map();for(const row of unresolved||[]){const id=String(row.deckId),deck=grouped.get(id)||{id,name:row.deckName||'Mazzo',game:'yugioh',deckTheme:'arcane-purple',cards:[],marketValue:null,delta24:null,delta7:null,topMover:null,totalCopies:0,valuedCopies:0,unresolvedCount:0};deck.cards.push({catalogCardId:row.catalogCardId,cardName:row.cardName,section:row.section,quantity:row.quantity,imageUrl:''});deck.totalCopies+=row.quantity;deck.unresolvedCount+=row.quantity;grouped.set(id,deck);}return [...grouped.values()];
}
export function portfolioSummary(items,now=Date.now()){const owned=items.filter(item=>item.sources.includes('owned')&&item.ownedQuantity>0),totalUnits=owned.reduce((sum,item)=>sum+item.ownedQuantity,0),fresh=owned.filter(item=>item.referencePrice!=null&&item.latestAt&&now-new Date(item.latestAt).getTime()<=FRESH_MS),coveredUnits=fresh.reduce((sum,item)=>sum+item.ownedQuantity,0),coverage=totalUnits?coveredUnits/totalUnits:0,current=fresh.reduce((sum,item)=>sum+item.referencePrice*item.ownedQuantity,0),with24=fresh.filter(item=>item.price24h!=null),with7=fresh.filter(item=>item.price7d!=null),old24=with24.reduce((sum,item)=>sum+item.price24h*item.ownedQuantity,0),current24=with24.reduce((sum,item)=>sum+item.referencePrice*item.ownedQuantity,0),old7=with7.reduce((sum,item)=>sum+item.price7d*item.ownedQuantity,0),current7=with7.reduce((sum,item)=>sum+item.referencePrice*item.ownedQuantity,0);return {totalUnits,coveredUnits,totalPrintings:owned.length,coveredPrintings:fresh.length,freshPrintings:items.filter(item=>item.latestAt&&now-new Date(item.latestAt).getTime()<=FRESH_MS).length,coverage,current,complete:totalUnits>0&&coverage>=.9,delta24:current24-old24,delta24Percent:old24?((current24-old24)/old24)*100:null,delta24Complete:fresh.length>0&&with24.length===fresh.length&&coverage>=.9,delta7:current7-old7,delta7Percent:old7?((current7-old7)/old7)*100:null,delta7Complete:fresh.length>0&&with7.length===fresh.length&&coverage>=.9};}
export function deduplicateMonitored({owned=[],deck=[],manual=[]}={}){const map=new Map();for(const [source,rows] of Object.entries({owned,deck,manual}))for(const row of rows){if(!row.printingId)continue;const entry=map.get(row.printingId)||{printingId:row.printingId,sources:new Set(),quantity:0};entry.sources.add(source);if(source==='owned')entry.quantity+=Number(row.quantity||0);map.set(row.printingId,entry);}return [...map.values()].map(row=>({...row,sources:[...row.sources]}));}
export function providerWarning(providers){const values=Object.values(providers||{}).map(row=>Number(row.price)).filter(Number.isFinite);if(values.length<2)return null;const low=Math.min(...values),high=Math.max(...values);if(low<=0)return null;const spread=(high-low)/low*100;return spread>=20?Math.round(spread):null;}
export function positiveMovers(items,limit=3){const ranked=(items||[]).filter(item=>item.sources?.includes('owned')&&Number.isFinite(item.referencePrice)&&Number.isFinite(item.price24h)&&item.price24h>0&&item.referencePrice>item.price24h).map(item=>({...item,positiveChange:(item.referencePrice-item.price24h)/item.price24h*100})).sort((a,b)=>b.positiveChange-a.positiveChange||(b.referencePrice-b.price24h)-(a.referencePrice-a.price24h));const seen=new Set(),result=[];for(const item of ranked){const key=String(item.catalogCardId||item.cardName).toLowerCase();if(seen.has(key))continue;seen.add(key);result.push(item);if(result.length>=limit)break;}return result;}
export function mapDashboardMovers(rows=[]){return (Array.isArray(rows)?rows:[]).map(row=>({printingId:row.printingId||row.printing_id,catalogCardId:String(row.catalogCardId||row.catalog_card_id||''),cardName:row.cardName||row.card_name||'',setCode:row.setCode||row.set_code||'',setName:row.setName||row.set_name||'',rarity:row.rarity||'',imageUrl:row.imageUrl||row.image_url||'',ownedQuantity:Number(row.ownedQuantity??row.owned_quantity??0),referencePrice:nullableNumber(row.referencePrice??row.reference_price),baselinePrice:nullableNumber(row.baselinePrice??row.baseline_price),positiveChange:nullableNumber(row.positiveChange??row.positive_change),capturedAt:row.capturedAt||row.captured_at||null,sparkline:(row.sparkline||[]).map(point=>({label:point.label||'',price:nullableNumber(point.price),order:Number(point.order||0)})).filter(point=>point.price!=null).sort((a,b)=>a.order-b.order)}));}

function marketRow(item){const delta=item.referencePrice!=null&&item.price24h!=null?item.referencePrice-item.price24h:null,percent=delta!=null&&item.price24h?delta/item.price24h*100:null,total=item.referencePrice==null?null:item.referencePrice*item.ownedQuantity;return `<button class="market-row" data-market-card="${esc(item.printingId)}">${item.imageUrl?`<img src="${esc(item.imageUrl)}" alt="">`:`<span class="market-art-empty">${icon('card')}</span>`}<span class="market-card-copy"><strong>${esc(item.cardName)}</strong><small>${esc(item.setCode||'Set non indicato')} · ${esc(item.rarity||'Rarità non indicata')}</small><em>${item.sources.map(source=>LABELS[source]).join(' · ')}${item.sources.includes('owned')?` · ${item.ownedQuantity} copie`:''}</em></span><span class="market-price"><strong>${item.referencePrice==null?'—':money(item.referencePrice)}</strong><small>${total==null?'In attesa prezzo':`Valore ${money(total)}`}</small><small class="${tone(delta)}">${delta==null?'Primo snapshot':`${changeMoney(delta)} · ${changePercent(percent)}`}</small></span>${icon('arrow')}</button>`;}
export function sortItems(items,mode='value'){return [...items].sort((a,b)=>{if(mode==='name')return a.cardName.localeCompare(b.cardName,'it');if(mode==='price')return (b.referencePrice??-1)-(a.referencePrice??-1);if(mode==='change'){const av=a.referencePrice!=null&&a.price24h!=null?a.referencePrice-a.price24h:-Infinity,bv=b.referencePrice!=null&&b.price24h!=null?b.referencePrice-b.price24h:-Infinity;return bv-av;}return ((b.referencePrice??-1)*b.ownedQuantity)-((a.referencePrice??-1)*a.ownedQuantity);});}
function priceChart(rows){const points=(rows||[]).filter(row=>Number.isFinite(row.price)).sort((a,b)=>new Date(a.capturedAt)-new Date(b.capturedAt));if(points.length<2)return'<div class="market-detail-empty">Il grafico comparirà dopo almeno due snapshot giornalieri.</div>';const values=points.map(row=>row.price),min=Math.min(...values),max=Math.max(...values),span=max-min||1,width=320,height=120,pad=8,path=points.map((row,index)=>`${index?'L':'M'} ${pad+(index/(points.length-1))*(width-pad*2)} ${height-pad-((row.price-min)/span)*(height-pad*2)}`).join(' ');return `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Andamento prezzo"><path d="${path}" fill="none" stroke="currentColor" stroke-width="3" vector-effect="non-scaling-stroke"/><circle cx="${width-pad}" cy="${height-pad-((values.at(-1)-min)/span)*(height-pad*2)}" r="4"/></svg><div><span>${money(min)}</span><strong>${money(values.at(-1))}</strong><span>${money(max)}</span></div>`;}
function unresolvedDeckRow(row){return `<article class="market-row unresolved"><span class="market-art-empty">${icon('deck')}</span><span class="market-card-copy"><strong>${esc(row.cardName)}</strong><small>${esc(row.deckName)} · ${esc(row.section)} · ${row.quantity} copie</small><em>Printing da selezionare</em></span><button class="btn secondary small" data-market-resolve-deck>Seleziona</button></article>`;}
function emptyPreparing(){return '<div class="market-preparing"><span class="market-orbit">'+icon('chart')+'</span><div><h2>Il Market Watch sta preparando i primi dati.</h2><p>Le printing sono pronte; i valori compariranno dopo il primo aggiornamento server-side.</p></div></div>';}
function emptyNoCards(){return '<div class="empty-state market-empty">'+icon('collection')+'<h2>Aggiungi carte alla Raccolta o alla Watchlist per iniziare.</h2><p>Le carte possedute entrano automaticamente nel monitoraggio.</p></div>';}
function kpi(label,value,detail,kind){return `<article class="surface market-kpi ${kind}"><small>${label}</small><strong>${value}</strong><span>${detail}</span></article>`;}
function countFor(data,tab,deckCount=0){return tab==='deck'?deckCount:data.items.filter(item=>item.sources.includes(tab)).length;}
function normalizeProviders(value){if(!value||typeof value!=='object')return{};return Object.fromEntries(Object.entries(value).map(([key,row])=>[key,{...row,capturedAt:row.capturedAt||row.captured_at,conditionReference:row.conditionReference||row.condition_reference,price:nullableNumber(row.price)}]));}
function nullableNumber(value){if(value==null||value==='')return null;const number=Number(value);return Number.isFinite(number)?number:null;}
function money(value){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(value)||0);}
function changeMoney(value){const number=Number(value)||0;return `${number>=0?'+':'−'}${money(Math.abs(number))}`;}
function changePercent(value){if(value==null)return'—';const number=Number(value)||0;return `${number>=0?'+':'−'}${Math.abs(number).toFixed(1)}%`;}
function tone(value){return value==null?'muted':value>0?'positive':value<0?'negative':'muted';}
function formatTimestamp(value){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(date);}
function providerName(value){return value==='cardtrader'?'CardTrader':value==='cardmarket'?'Cardmarket':value;}
