import {esc} from './core.js';
import {icon} from './icons.js';

const TABS=['owned','deck','manual'];
const LABELS={owned:'Owned',deck:'Deck',manual:'Watchlist'};
const FRESH_MS=48*60*60*1000;

export class MarketWatchController {
  constructor({api,getGame,onRender,onToast,onNavigate}={}){Object.assign(this,{api,getGame,onRender,onToast,onNavigate});this.data={items:[],deckUnresolved:[],lastSync:null};this.tab='owned';this.loading=false;this.error='';this.selected='';}
  async load(){this.loading=true;try{const payload=await this.api.marketWatch(this.getGame());this.data=mapPayload(payload);this.error='';}catch(error){this.error=/list_market_watch/i.test(error.message||'')?'Applica la migration Market Watch per attivare i dati.':(error.message||'Market Watch non disponibile');}finally{this.loading=false;}return this.data;}
  view(){const summary=portfolioSummary(this.data.items),items=this.data.items.filter(item=>item.sources.includes(this.tab)),unresolved=this.tab==='deck'?this.data.deckUnresolved:[],hasSnapshots=this.data.items.some(item=>item.referencePrice!=null);
    return `<section class="page-stack market-page"><header class="market-hero"><div><span class="eyebrow">Valore e andamento</span><h1>Market Watch</h1><p>Segui le printing esatte della raccolta, dei mazzi e della watchlist.</p></div><div class="market-sync-state"><i class="${this.error?'error':this.data.lastSync?'ok':'waiting'}"></i><span><small>Ultimo aggiornamento</small><strong>${this.data.lastSync?formatTimestamp(this.data.lastSync):'In attesa del primo sync'}</strong></span></div></header>
      ${this.error?`<div class="connection-banner error">${esc(this.error)}</div>`:''}
      <section class="market-kpis">
        ${kpi('Valore raccolta',summary.complete?money(summary.current):'Dati parziali',summary.complete?`${summary.coveredUnits}/${summary.totalUnits} copie valorizzate`:`Dati parziali · ${summary.coveredPrintings}/${summary.totalPrintings} printing valorizzate`,'value')}
        ${kpi('Variazione 24h',summary.delta24Complete?changeMoney(summary.delta24):'Dati parziali',summary.delta24Complete?changePercent(summary.delta24Percent):'Snapshot non sufficiente',tone(summary.delta24))}
        ${kpi('Variazione 7d',summary.delta7Complete?changeMoney(summary.delta7):'Dati parziali',summary.delta7Complete?changePercent(summary.delta7Percent):'Snapshot non sufficiente',tone(summary.delta7))}
        ${kpi('Printing monitorate',String(this.data.items.length),`${summary.freshPrintings} aggiornate entro 48h`,'count')}
      </section>
      <section class="surface market-board"><nav class="market-tabs" aria-label="Filtri Market Watch">${TABS.map(tab=>`<button data-market-tab="${tab}" class="${this.tab===tab?'active':''}">${LABELS[tab]} <span>${countFor(this.data,tab)}</span></button>`).join('')}</nav>
        ${!this.data.items.length&&!unresolved.length?emptyNoCards():!hasSnapshots?`${emptyPreparing()}${this.rows(items,unresolved)}`:this.rows(items,unresolved)}
      </section>${this.selected?this.detailView():''}</section>`;}
  rows(items,unresolved){return `<div class="market-list">${unresolved.map(unresolvedDeckRow).join('')}${items.map(marketRow).join('')}${!items.length&&!unresolved.length?'<div class="market-tab-empty">Nessuna printing in questa sezione.</div>':''}</div>`;}
  detailView(){const item=this.data.items.find(row=>row.printingId===this.selected);if(!item)return'';const providers=Object.entries(item.providers||{}),warning=providerWarning(item.providers);
    return `<div class="detail-backdrop" data-market-detail-close><aside class="card-detail market-detail" role="dialog" aria-modal="true"><button class="detail-close" data-market-detail-close aria-label="Chiudi">×</button><div class="market-detail-head">${item.imageUrl?`<img src="${esc(item.imageUrl)}" alt="">`:icon('card')}<div><span class="eyebrow">Dettaglio printing</span><h2>${esc(item.cardName)}</h2><p>${esc(item.setCode||'Set non indicato')} · ${esc(item.rarity||'Rarità non indicata')}</p></div></div><h3>Valori provider</h3>${providers.length?`<div class="provider-price-list">${providers.map(([name,value])=>`<article><span><strong>${providerName(name)}</strong><small>${esc(value.type||'prezzo')} · ${formatTimestamp(value.capturedAt)}</small></span><b>${money(value.price)}</b><em>${esc(value.conditionReference||'Riferimento provider')}</em></article>`).join('')}</div>`:'<div class="market-detail-empty">Nessuno snapshot disponibile.</div>'}${warning?`<p class="provider-warning">${icon('info')} Prezzi discordanti tra marketplace (${warning}% di differenza).</p>`:''}${item.sources.includes('manual')?`<button class="btn secondary danger wide" data-market-unwatch="${esc(item.printingId)}">Rimuovi dalla Watchlist</button>`:''}</aside></div>`;}
  bind(root=document){root.querySelectorAll('[data-market-tab]').forEach(button=>button.addEventListener('click',()=>{this.tab=button.dataset.marketTab;this.selected='';this.onRender();}));root.querySelectorAll('[data-market-card]').forEach(button=>button.addEventListener('click',()=>{this.selected=button.dataset.marketCard;this.onRender();}));root.querySelectorAll('[data-market-detail-close]').forEach(node=>node.addEventListener('click',event=>{if(event.target!==node&&!event.target.closest('.detail-close'))return;this.selected='';this.onRender();}));root.querySelectorAll('[data-market-unwatch]').forEach(button=>button.addEventListener('click',()=>void this.unwatch(button.dataset.marketUnwatch)));root.querySelectorAll('[data-market-resolve-deck]').forEach(button=>button.addEventListener('click',()=>this.onNavigate('decks')));}
  async unwatch(printingId){try{await this.api.setMarketWatchItem(printingId,false);await this.load();this.selected='';this.onToast('Printing rimossa dalla Watchlist');}catch(error){this.onToast(error.message||'Operazione non riuscita');}this.onRender();}
}

export function mapPayload(payload={}){return {items:(payload.items||[]).map(row=>({printingId:row.printing_id||row.printingId,catalogCardId:String(row.catalog_card_id||row.catalogCardId||''),cardName:row.card_name||row.cardName||'',setCode:row.set_code||row.setCode||'',setName:row.set_name||row.setName||'',rarity:row.rarity||'',imageUrl:row.image_url||row.imageUrl||'',sources:Array.isArray(row.sources)?row.sources:[],ownedQuantity:Number(row.owned_quantity??row.ownedQuantity??0),providers:normalizeProviders(row.providers),referencePrice:nullableNumber(row.reference_price??row.referencePrice),price24h:nullableNumber(row.price_24h??row.price24h),price7d:nullableNumber(row.price_7d??row.price7d),latestAt:row.latest_at||row.latestAt||null})),deckUnresolved:(payload.deckUnresolved||payload.deck_unresolved||[]).map(row=>({deckId:row.deckId||row.deck_id,deckName:row.deckName||row.deck_name,cardName:row.cardName||row.card_name,catalogCardId:String(row.catalogCardId||row.catalog_card_id||''),section:row.section,quantity:Number(row.quantity||0)})),lastSync:payload.lastSync||payload.last_sync||null};}
export function portfolioSummary(items,now=Date.now()){const owned=items.filter(item=>item.sources.includes('owned')&&item.ownedQuantity>0),totalUnits=owned.reduce((sum,item)=>sum+item.ownedQuantity,0),fresh=owned.filter(item=>item.referencePrice!=null&&item.latestAt&&now-new Date(item.latestAt).getTime()<=FRESH_MS),coveredUnits=fresh.reduce((sum,item)=>sum+item.ownedQuantity,0),coverage=totalUnits?coveredUnits/totalUnits:0,current=fresh.reduce((sum,item)=>sum+item.referencePrice*item.ownedQuantity,0),with24=fresh.filter(item=>item.price24h!=null),with7=fresh.filter(item=>item.price7d!=null),old24=with24.reduce((sum,item)=>sum+item.price24h*item.ownedQuantity,0),current24=with24.reduce((sum,item)=>sum+item.referencePrice*item.ownedQuantity,0),old7=with7.reduce((sum,item)=>sum+item.price7d*item.ownedQuantity,0),current7=with7.reduce((sum,item)=>sum+item.referencePrice*item.ownedQuantity,0);return {totalUnits,coveredUnits,totalPrintings:owned.length,coveredPrintings:fresh.length,freshPrintings:items.filter(item=>item.latestAt&&now-new Date(item.latestAt).getTime()<=FRESH_MS).length,coverage,current,complete:totalUnits>0&&coverage>=.9,delta24:current24-old24,delta24Percent:old24?((current24-old24)/old24)*100:null,delta24Complete:fresh.length>0&&with24.length===fresh.length&&coverage>=.9,delta7:current7-old7,delta7Percent:old7?((current7-old7)/old7)*100:null,delta7Complete:fresh.length>0&&with7.length===fresh.length&&coverage>=.9};}
export function deduplicateMonitored({owned=[],deck=[],manual=[]}={}){const map=new Map();for(const [source,rows] of Object.entries({owned,deck,manual}))for(const row of rows){if(!row.printingId)continue;const entry=map.get(row.printingId)||{printingId:row.printingId,sources:new Set(),quantity:0};entry.sources.add(source);if(source==='owned')entry.quantity+=Number(row.quantity||0);map.set(row.printingId,entry);}return [...map.values()].map(row=>({...row,sources:[...row.sources]}));}
export function providerWarning(providers){const values=Object.values(providers||{}).map(row=>Number(row.price)).filter(Number.isFinite);if(values.length<2)return null;const low=Math.min(...values),high=Math.max(...values);if(low<=0)return null;const spread=(high-low)/low*100;return spread>=20?Math.round(spread):null;}

function marketRow(item){const delta=item.referencePrice!=null&&item.price24h!=null?item.referencePrice-item.price24h:null,percent=delta!=null&&item.price24h?delta/item.price24h*100:null;return `<button class="market-row" data-market-card="${esc(item.printingId)}">${item.imageUrl?`<img src="${esc(item.imageUrl)}" alt="">`:`<span class="market-art-empty">${icon('card')}</span>`}<span class="market-card-copy"><strong>${esc(item.cardName)}</strong><small>${esc(item.setCode||'Set non indicato')} · ${esc(item.rarity||'Rarità non indicata')}</small><em>${item.sources.map(source=>LABELS[source]).join(' · ')}</em></span><span class="market-price"><strong>${item.referencePrice==null?'—':money(item.referencePrice)}</strong><small class="${tone(delta)}">${delta==null?'Primo snapshot':`${changeMoney(delta)} · ${changePercent(percent)}`}</small></span>${icon('arrow')}</button>`;}
function unresolvedDeckRow(row){return `<article class="market-row unresolved"><span class="market-art-empty">${icon('deck')}</span><span class="market-card-copy"><strong>${esc(row.cardName)}</strong><small>${esc(row.deckName)} · ${esc(row.section)} · ${row.quantity} copie</small><em>Printing da selezionare</em></span><button class="btn secondary small" data-market-resolve-deck>Seleziona</button></article>`;}
function emptyPreparing(){return '<div class="market-preparing"><span class="market-orbit">'+icon('chart')+'</span><div><h2>Il Market Watch sta preparando i primi dati.</h2><p>Le printing sono pronte; i valori compariranno dopo il primo aggiornamento server-side.</p></div></div>';}
function emptyNoCards(){return '<div class="empty-state market-empty">'+icon('collection')+'<h2>Aggiungi carte alla Raccolta o alla Watchlist per iniziare.</h2><p>Le carte possedute entrano automaticamente nel monitoraggio.</p></div>';}
function kpi(label,value,detail,kind){return `<article class="surface market-kpi ${kind}"><small>${label}</small><strong>${value}</strong><span>${detail}</span></article>`;}
function countFor(data,tab){return tab==='deck'?data.items.filter(item=>item.sources.includes(tab)).length+data.deckUnresolved.length:data.items.filter(item=>item.sources.includes(tab)).length;}
function normalizeProviders(value){if(!value||typeof value!=='object')return{};return Object.fromEntries(Object.entries(value).map(([key,row])=>[key,{...row,capturedAt:row.capturedAt||row.captured_at,conditionReference:row.conditionReference||row.condition_reference,price:nullableNumber(row.price)}]));}
function nullableNumber(value){if(value==null||value==='')return null;const number=Number(value);return Number.isFinite(number)?number:null;}
function money(value){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(value)||0);}
function changeMoney(value){const number=Number(value)||0;return `${number>=0?'+':'−'}${money(Math.abs(number))}`;}
function changePercent(value){if(value==null)return'—';const number=Number(value)||0;return `${number>=0?'+':'−'}${Math.abs(number).toFixed(1)}%`;}
function tone(value){return value==null?'muted':value>0?'positive':value<0?'negative':'muted';}
function formatTimestamp(value){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(date);}
function providerName(value){return value==='cardtrader'?'CardTrader':value==='cardmarket'?'Cardmarket':value;}
